name: Build and publish

on:
  release:
    types: [published]

env:
  PUBLISHEDFILEID: 1616051926
  CHANGELOG: "[b]${{ github.event.release.name }}[/b] (${{ github.event.release.tag_name }})\n\n${{ github.event.release.body }}\n\n${{ github.event.release.html_url }}"

jobs:
  publish:
    name: Publish to GitHub Release and Steam Workshop
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy to /dist
        run: |
          mkdir "./dist"
          find . -maxdepth 1 -not -path "./dist" -not -path "." -not -path "./.*" -exec mv --target-directory "./dist" {} +

      - name: Add files to Github release
        run: |
          echo '{"version": "${{ github.event.release.tag_name }}"}' > ./dist/version.json
          (cd ./dist && zip -r ../release.zip .)

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: ${{ github.event.repository.name }}-release.zip
          asset_content_type: application/zip

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1
        
      - name: Prompt 2FA code
        id: prompt
        uses: TechnologicNick/actions-discord-prompt@master
        with:
          discord_token: ${{ secrets.DISCORD_TOKEN }}
          discord_guild: ${{ secrets.DISCORD_GUILD }}
          discord_channel: ${{ secrets.DISCORD_CHANNEL }}
          prompts: '[
            {
              "name": "code_2fa",
              "message": {
                "content": null,
                "embeds": [{
                  "title": "Please enter your two factor authentication code",
                  "description": "/2fa <code>",
                  "color": 5793266
                }]
              },
              "type": "COMMAND",
              "options": {
                "name": "2fa",
                "description": "Please enter your two factor authentication code",
                "options": [{
                  "name": "code",
                  "type": "STRING",
                  "description": "The Steam Guard code",
                  "required": true
                }]
              },
              "onSuccess": {
                "content": null,
                "embeds": [{
                  "title": "Entered 2FA code",
                  "color": 5763719
                }]
              }
            }
          ]'
      
      - name: Write workshop.vdf
        run: |
          cat << EOF > ./workshop.vdf
          "workshopitem"
          {
              "appid"            "387990"
              "publishedfileid"  "$PUBLISHEDFILEID"
              "contentfolder"    "$GITHUB_WORKSPACE/dist"
              "changenote"       "$CHANGELOG"
          }
          EOF
          
          cat ./workshop.vdf
      
      - name: Push to Steam Workshop
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_2FA: ${{ fromJSON(steps.prompt.outputs.code_2fa).options.code }}
        run: |
          steamcmd +login $STEAM_USERNAME $STEAM_PASSWORD $STEAM_2FA +workshop_build_item workshop.vdf +quit
